from dataclasses import dataclass
from typing import Any

import pandas as pd

from stock_selector.data.data_validator import DataValidationError, validate_stock_code
from stock_selector.storage.partition import validate_dataset
from stock_selector.utils.date_validator import validate_trade_date


REQUIRED_BENCHMARK_INDEXES = {"000300.SH", "000905.SH", "000906.SH"}


@dataclass(frozen=True)
class SchemaContract:
    dataset: str
    columns: list[str]
    numeric_columns: list[str]
    bool_columns: list[str]
    date_columns: list[str]
    nullable_columns: list[str]


SCHEMA_CONTRACTS = {
    "stock_basic": SchemaContract(
        dataset="stock_basic",
        columns=["stock_code", "stock_name", "exchange", "list_date", "delist_date", "industry", "market_type", "is_st", "trade_date"],
        numeric_columns=[],
        bool_columns=["is_st"],
        date_columns=["list_date", "delist_date", "trade_date"],
        nullable_columns=["delist_date"],
    ),
    "daily_price": SchemaContract(
        dataset="daily_price",
        columns=[
            "stock_code",
            "trade_date",
            "open",
            "high",
            "low",
            "close",
            "pre_close",
            "volume",
            "amount",
            "pct_chg",
            "is_paused",
            "limit_up",
            "limit_down",
        ],
        numeric_columns=["open", "high", "low", "close", "pre_close", "volume", "amount", "pct_chg", "limit_up", "limit_down"],
        bool_columns=["is_paused"],
        date_columns=["trade_date"],
        nullable_columns=[],
    ),
    "adj_factor": SchemaContract(
        dataset="adj_factor",
        columns=["stock_code", "trade_date", "adj_factor"],
        numeric_columns=["adj_factor"],
        bool_columns=[],
        date_columns=["trade_date"],
        nullable_columns=[],
    ),
    "daily_basic": SchemaContract(
        dataset="daily_basic",
        columns=["stock_code", "trade_date", "pe_ttm", "pb", "ps_ttm", "total_mv", "circ_mv", "turnover_rate"],
        numeric_columns=["pe_ttm", "pb", "ps_ttm", "total_mv", "circ_mv", "turnover_rate"],
        bool_columns=[],
        date_columns=["trade_date"],
        nullable_columns=[],
    ),
    "financial": SchemaContract(
        dataset="financial",
        columns=[
            "stock_code",
            "report_period",
            "announce_date",
            "revenue_yoy",
            "net_profit_yoy",
            "roe",
            "gross_margin",
            "debt_ratio",
            "operating_cashflow",
        ],
        numeric_columns=["revenue_yoy", "net_profit_yoy", "roe", "gross_margin", "debt_ratio", "operating_cashflow"],
        bool_columns=[],
        date_columns=["report_period", "announce_date"],
        nullable_columns=[],
    ),
    "st_history": SchemaContract(
        dataset="st_history",
        columns=["stock_code", "st_type", "start_date", "end_date", "source"],
        numeric_columns=[],
        bool_columns=[],
        date_columns=["start_date", "end_date"],
        nullable_columns=["end_date"],
    ),
    "benchmark_price": SchemaContract(
        dataset="benchmark_price",
        columns=["index_code", "trade_date", "open", "high", "low", "close", "pct_chg"],
        numeric_columns=["open", "high", "low", "close", "pct_chg"],
        bool_columns=[],
        date_columns=["trade_date"],
        nullable_columns=[],
    ),
    "adjusted_price": SchemaContract(
        dataset="adjusted_price",
        columns=[
            "stock_code",
            "trade_date",
            "adj_open",
            "adj_high",
            "adj_low",
            "adj_close",
            "volume",
            "amount",
            "pct_chg",
            "is_paused",
            "limit_up",
            "limit_down",
        ],
        numeric_columns=["adj_open", "adj_high", "adj_low", "adj_close", "volume", "amount", "pct_chg", "limit_up", "limit_down"],
        bool_columns=["is_paused"],
        date_columns=["trade_date"],
        nullable_columns=[],
    ),
    "clean_daily_snapshot": SchemaContract(
        dataset="clean_daily_snapshot",
        columns=[
            "stock_code",
            "trade_date",
            "stock_name",
            "industry",
            "market_type",
            "open",
            "high",
            "low",
            "close",
            "pre_close",
            "volume",
            "amount",
            "pct_chg",
            "is_paused",
            "limit_up",
            "limit_down",
            "adj_open",
            "adj_high",
            "adj_low",
            "adj_close",
            "pe_ttm",
            "pb",
            "ps_ttm",
            "total_mv",
            "circ_mv",
            "turnover_rate",
            "report_period",
            "announce_date",
            "revenue_yoy",
            "net_profit_yoy",
            "roe",
            "gross_margin",
            "debt_ratio",
            "operating_cashflow",
            "is_st_on_date",
            "listed_days",
        ],
        numeric_columns=[
            "open",
            "high",
            "low",
            "close",
            "pre_close",
            "volume",
            "amount",
            "pct_chg",
            "limit_up",
            "limit_down",
            "adj_open",
            "adj_high",
            "adj_low",
            "adj_close",
            "pe_ttm",
            "pb",
            "ps_ttm",
            "total_mv",
            "circ_mv",
            "turnover_rate",
            "revenue_yoy",
            "net_profit_yoy",
            "roe",
            "gross_margin",
            "debt_ratio",
            "operating_cashflow",
            "listed_days",
        ],
        bool_columns=["is_paused", "is_st_on_date"],
        date_columns=["trade_date", "report_period", "announce_date"],
        nullable_columns=[
            "report_period",
            "announce_date",
            "revenue_yoy",
            "net_profit_yoy",
            "roe",
            "gross_margin",
            "debt_ratio",
            "operating_cashflow",
        ],
    ),
    "risk_filter": SchemaContract(
        dataset="risk_filter",
        columns=[
            "stock_code",
            "trade_date",
            "is_eligible",
            "exclude_reasons",
            "risk_flags",
            "is_st_on_date",
            "is_paused",
            "listed_days",
            "amount",
            "roe",
            "debt_ratio",
            "report_period",
            "announce_date",
        ],
        numeric_columns=["listed_days", "amount", "roe", "debt_ratio"],
        bool_columns=["is_eligible", "is_st_on_date", "is_paused"],
        date_columns=["trade_date", "report_period", "announce_date"],
        nullable_columns=["roe", "debt_ratio", "report_period", "announce_date"],
    ),
    "eligible_universe": SchemaContract(
        dataset="eligible_universe",
        columns=[
            "stock_code",
            "trade_date",
            "stock_name",
            "industry",
            "market_type",
            "listed_days",
            "amount",
            "roe",
            "debt_ratio",
        ],
        numeric_columns=["listed_days", "amount", "roe", "debt_ratio"],
        bool_columns=[],
        date_columns=["trade_date"],
        nullable_columns=[],
    ),
    "factor_input_table": SchemaContract(
        dataset="factor_input_table",
        columns=[
            "stock_code",
            "trade_date",
            "industry",
            "market_type",
            "adj_close",
            "amount",
            "turnover_rate",
            "pe_ttm",
            "pb",
            "ps_ttm",
            "total_mv",
            "circ_mv",
            "revenue_yoy",
            "net_profit_yoy",
            "roe",
            "gross_margin",
            "debt_ratio",
            "operating_cashflow",
        ],
        numeric_columns=[
            "adj_close",
            "amount",
            "turnover_rate",
            "pe_ttm",
            "pb",
            "ps_ttm",
            "total_mv",
            "circ_mv",
            "revenue_yoy",
            "net_profit_yoy",
            "roe",
            "gross_margin",
            "debt_ratio",
            "operating_cashflow",
        ],
        bool_columns=[],
        date_columns=["trade_date"],
        nullable_columns=[],
    ),
    "factor_daily": SchemaContract(
        dataset="factor_daily",
        columns=[
            "stock_code",
            "trade_date",
            "industry",
            "market_type",
            "quality_roe",
            "quality_gross_margin",
            "quality_debt_ratio",
            "quality_cashflow_profit_ratio",
            "growth_revenue_yoy",
            "growth_net_profit_yoy",
            "valuation_pe_ttm",
            "valuation_pb",
            "valuation_ps_ttm",
            "valuation_pe_percentile_3y",
            "valuation_pb_percentile_3y",
            "trend_ret_20d",
            "trend_ret_60d",
            "trend_ret_120d",
            "trend_ma20",
            "trend_ma60",
            "trend_ma120",
            "trend_price_ma60_ratio",
            "industry_ret_60d",
            "industry_ret_120d",
            "industry_strength_60d",
            "industry_strength_120d",
            "liquidity_amount",
            "liquidity_turnover_rate",
            "quality_score",
            "growth_score",
            "valuation_score",
            "trend_score",
            "industry_score",
        ],
        numeric_columns=[
            "quality_roe",
            "quality_gross_margin",
            "quality_debt_ratio",
            "quality_cashflow_profit_ratio",
            "growth_revenue_yoy",
            "growth_net_profit_yoy",
            "valuation_pe_ttm",
            "valuation_pb",
            "valuation_ps_ttm",
            "valuation_pe_percentile_3y",
            "valuation_pb_percentile_3y",
            "trend_ret_20d",
            "trend_ret_60d",
            "trend_ret_120d",
            "trend_ma20",
            "trend_ma60",
            "trend_ma120",
            "trend_price_ma60_ratio",
            "industry_ret_60d",
            "industry_ret_120d",
            "industry_strength_60d",
            "industry_strength_120d",
            "liquidity_amount",
            "liquidity_turnover_rate",
            "quality_score",
            "growth_score",
            "valuation_score",
            "trend_score",
            "industry_score",
        ],
        bool_columns=[],
        date_columns=["trade_date"],
        nullable_columns=[
            "quality_cashflow_profit_ratio",
            "trend_ret_20d",
            "trend_ret_60d",
            "trend_ret_120d",
            "trend_ma20",
            "trend_ma60",
            "trend_ma120",
            "trend_price_ma60_ratio",
            "industry_ret_60d",
            "industry_ret_120d",
            "industry_strength_60d",
            "industry_strength_120d",
        ],
    ),
    "selection_result": SchemaContract(
        dataset="selection_result",
        columns=[
            "stock_code",
            "trade_date",
            "industry",
            "market_type",
            "quality_score",
            "growth_score",
            "valuation_score",
            "trend_score",
            "industry_score",
            "total_score",
            "risk_level",
            "rank",
            "suggestion",
            "reason",
            "exclude_reasons",
            "risk_flags",
        ],
        numeric_columns=[
            "quality_score",
            "growth_score",
            "valuation_score",
            "trend_score",
            "industry_score",
            "total_score",
            "rank",
        ],
        bool_columns=[],
        date_columns=["trade_date"],
        nullable_columns=[],
    ),
}


def get_schema_contract(dataset: str) -> SchemaContract:
    dataset = validate_dataset(dataset)
    return SCHEMA_CONTRACTS[dataset]


def inspect_schema(dataset: str) -> dict[str, Any]:
    contract = get_schema_contract(dataset)
    return {
        "dataset": contract.dataset,
        "columns": contract.columns,
        "numeric_columns": contract.numeric_columns,
        "bool_columns": contract.bool_columns,
        "date_columns": contract.date_columns,
        "nullable_columns": contract.nullable_columns,
    }


def validate_benchmark_contract(df: pd.DataFrame) -> None:
    missing = sorted(REQUIRED_BENCHMARK_INDEXES - set(df["index_code"].astype(str)))
    if missing:
        raise DataValidationError(f"missing benchmark indexes: {', '.join(missing)}")


def is_st_on_date(st_history: pd.DataFrame, stock_code: str, trade_date: str) -> bool:
    stock_code = validate_stock_code(stock_code)
    trade_date = validate_trade_date(trade_date)
    for row in st_history.to_dict(orient="records"):
        if str(row["stock_code"]) != stock_code:
            continue
        start_date = validate_trade_date(str(row["start_date"]))
        end_value = row.get("end_date")
        end_date = None if pd.isna(end_value) else validate_trade_date(str(end_value))
        if start_date <= trade_date and (end_date is None or end_date > trade_date):
            return True
    return False

